package me.notlewx.privategames.config.proxy;

import me.notlewx.privategames.config.ConfigManager;
import org.bukkit.Bukkit;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.Plugin;
import static me.notlewx.privategames.config.bedwars1058.MainConfig.*;

public class MainConfig extends ConfigManager {
    public MainConfig(Plugin plugin, String name) {
        super(plugin, name, Bukkit.getWorldContainer().getPath() + "/plugins/BedWarsProxy/Addons/PrivateGames/");
        YamlConfiguration yml = getYml();
        yml.options().header("BedWars1058 PrivateGames Addon by Kiiya#9207");
        yml.addDefault(SPEED, true);
        yml.addDefault(ONE_HIT_ONE_KILL, true);
        yml.addDefault(HEALTH_BUFF, true);
        yml.addDefault(LONG_JUMP, true);
        yml.addDefault(BED_INSTA_BREAK, true);
        yml.addDefault(RESPAWN_TIME, true);
        yml.addDefault(EVENTS_TIME, true);
        yml.addDefault(MAX_TEAM_UPGRADES, true);
        yml.addDefault(ALLOW_MAP_BREAK, true);
        yml.addDefault(NO_DIAMONDS, true);
        yml.addDefault(NO_EMERALDS, true);
        yml.addDefault(GAMEMODE_CHANGER, true);
        yml.addDefault(SETTINGS_ROWS, 6);
        yml.addDefault(ONE_HIT_ONE_HILL_MATERIAL, "DIAMOND_SWORD");
        yml.addDefault(ONE_HIT_ONE_HILL_POSITION, 10);
        yml.addDefault(HEALTH_BUFF_MATERIAL, "GOLDEN_APPLE");
        yml.addDefault(HEALTH_BUFF_POSITION, 12);
        yml.addDefault(LONG_JUMP_MATERIAL, "QUARTZ");
        yml.addDefault(LONG_JUMP_POSITION, 14);
        yml.addDefault(SPEED_MATERIAL, "RABBIT_FOOT");
        yml.addDefault(SPEED_POSITION, 16);
        yml.addDefault(RESPAWN_TIME_MATERIAL, "PAPER");
        yml.addDefault(RESPAWN_TIME_POSITION, 20);
        yml.addDefault(EVENTS_TIME_MATERIAL, "BOOK");
        yml.addDefault(EVENTS_TIME_POSITION, 22);
        yml.addDefault(NO_EMERALDS_MATERIAL, "EMERALD");
        yml.addDefault(NO_EMERALDS_POSITION, 24);
        yml.addDefault(NO_DIAMONDS_MATERIAL, "DIAMOND");
        yml.addDefault(NO_DIAMONDS_POSITION, 28);
        yml.addDefault(ALLOW_MAP_BREAK_MATERIAL, "GRASS");
        yml.addDefault(ALLOW_MAP_BREAK_POSITION, 30);
        yml.addDefault(BED_INSTA_BREAK_MATERIAL, "BED");
        yml.addDefault(BED_INSTA_BREAK_POSITION, 32);
        yml.addDefault(MAX_TEAM_UPGRADES_MATERIAL, "DIAMOND_BLOCK");
        yml.addDefault(MAX_TEAM_UPGRADES_POSITION, 34);
        yml.addDefault(GAMEMODE_CHANGER_MATERIAL, "REDSTONE_COMPARATOR");
        yml.addDefault(GAMEMODE_CHANGER_POSITION, 53);
        yml.addDefault(BACK_MATERIAL, "ARROW");
        yml.addDefault(BACK_POSITION, 49);
        yml.addDefault(SPEED_MENU_ROWS, 3);
        yml.addDefault(SPEED_LEVEL_I_MATERIAL, "RABBIT_FOOT");
        yml.addDefault(SPEED_LEVEL_I_POSITION, 10);
        yml.addDefault(SPEED_LEVEL_II_MATERIAL, "RABBIT_FOOT");
        yml.addDefault(SPEED_LEVEL_II_POSITION, 12);
        yml.addDefault(SPEED_LEVEL_III_MATERIAL, "RABBIT_FOOT");
        yml.addDefault(SPEED_LEVEL_III_POSITION, 14);
        yml.addDefault(SPEED_LEVEL_IV_MATERIAL, "RABBIT_FOOT");
        yml.addDefault(SPEED_LEVEL_IV_POSITION, 16);
        yml.addDefault(RESPAWN_TIME_MENU_ROWS, 3);
        yml.addDefault(RESPAWN_TIME_LEVEL_I_MATERIAL, "PAPER");
        yml.addDefault(RESPAWN_TIME_LEVEL_I_POSITION, 11);
        yml.addDefault(RESPAWN_TIME_LEVEL_II_MATERIAL, "PAPER");
        yml.addDefault(RESPAWN_TIME_LEVEL_II_POSITION, 13);
        yml.addDefault(RESPAWN_TIME_LEVEL_III_MATERIAL, "PAPER");
        yml.addDefault(RESPAWN_TIME_LEVEL_III_POSITION, 15);
        yml.addDefault(EVENTS_TIME_MENU_ROWS, 3);
        yml.addDefault(EVENTS_TIME_LEVEL_I_MATERIAL, "BOOK");
        yml.addDefault(EVENTS_TIME_LEVEL_I_POSITION, 10);
        yml.addDefault(EVENTS_TIME_LEVEL_II_MATERIAL, "BOOK");
        yml.addDefault(EVENTS_TIME_LEVEL_II_POSITION, 12);
        yml.addDefault(EVENTS_TIME_LEVEL_III_MATERIAL, "BOOK");
        yml.addDefault(EVENTS_TIME_LEVEL_III_POSITION, 14);
        yml.addDefault(EVENTS_TIME_LEVEL_IV_MATERIAL, "BOOK");
        yml.addDefault(EVENTS_TIME_LEVEL_IV_POSITION, 16);
        yml.addDefault(HEALTH_BUFF_MENU_ROWS, 3);
        yml.addDefault(HEALTH_BUFF_LEVEL_I_MATERIAL, "GOLDEN_APPLE");
        yml.addDefault(HEALTH_BUFF_LEVEL_I_POSITION, 11);
        yml.addDefault(HEALTH_BUFF_LEVEL_II_MATERIAL, "GOLDEN_APPLE");
        yml.addDefault(HEALTH_BUFF_LEVEL_II_POSITION, 13);
        yml.addDefault(HEALTH_BUFF_LEVEL_III_MATERIAL, "GOLDEN_APPLE");
        yml.addDefault(HEALTH_BUFF_LEVEL_III_POSITION, 15);
        yml.addDefault(MATERIAL, "REDSTONE_BLOCK");
        yml.addDefault(POSITION, 0);
        yml.addDefault(ENCHANTED, false);
        yml.options().copyDefaults(true);
        save();
    }
}
