package me.notlewx.privategames.api.modifiers;

public enum ModifierType {
    ONE_HIT_ONE_KILL, HEALTH_BUFF, LOW_GRAVITY, SPEED, RESPAWN_TIME, EVENTS_TIME, NO_EMERALDS, NO_DIAMONDS, ALLOW_MAP_BREAK, INSTANT_BED_BREAK, MAX_TEAM_UPGRADES, CUSTOM
}
