name: PrivateGames
version: '1.1.9'
main: me.notlewx.privategames.PrivateGames
description: Private Games for bedwars like a well known server (with custom features)!
soft-dependencies: [ PlaceholderAPI, BedWars1058, BedWars2023, BedWarsProxy, BWProxy2023 ]
commands:
  pg:
    description: Main command of the plugin
    aliases:
      - privategame
      - private
      - pgame
